apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-app
  template:
    metadata:
      labels:
        app: stock-app
    spec:
      containers:
      - name: stock-app
        image: your-dockerhub-username/stock-app:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: stock-config
        - secretRef:
            name: stock-secret
